#Lenguaje de programación
language: python

#Indicamos que vamos a usar MongoDB y PostgreSQL
services:
  - mongodb
  - postgresql

#Distintas versiones para hacer la prueba
python:
  - "3.6"
  - "3.6.8" 
  - "3.7"
  - "3.8"
  - "3.8-dev"

#Instalar las dependencias necesarias
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database monitor;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD '$PASSWORD';" -U postgres

#Ejecutar los test unitarios y de cobertura
script:
  - invoke coverage

#Enviar resultados test de cobertura a codecov
after_success:
  - codecov
