#Lenguaje de programación
language: python

#Distintas versiones para hacer la prueba
python:
  - "3.6"
  - "3.7"
  - "3.8"

#Instalar las dependencias necesarias
install:
  - pip install -r requirements.txt

#Ejecutar los test
script:
  invoke test
  
after_success:
  invoke coverage