name: Python package

on: [push] #El workflow se activa al hacer push en el repositorio

jobs:
  build:

    runs-on: ${{ matrix.os }} #Los tests se corren en las últimas versiones de Windows, Ubuntu y MacOS
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8] #Versiones que se van a utilizar de Python
        os: [ubuntu-latest] #Versiones que se van a utilizar de los SO

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1 #Acción para levantar Python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar libpq-dev #Instalar este paquete necesario para utilizar el conector de PostgresSQL para Python
      run: sudo apt-get install libpq-dev --fix-missing
      
    - name: Instalar dependecias  #Instalamos pip y después instalamos las dependencias
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt 
        
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
      with:
        # MongoDB Version
        mongoDBVersion: 4.2
      
    - name: Testar con pytest #Instalamos Pytest y pasamos los test unitarios
      # Solo se testeará el servicio notifier con GitHub Actions
      # Con el servicio Monitor se producen fallos en la base de datos que impiden que se completen los tests
      run: |
        python3 -m pytest tests/test_N*.py tests/test_n*.py
      env: # Or as an environment variable
        FLASK_APP: ${{ secrets.FLASK_APP }}
        FLASK_ENV:  ${{ secrets.FLASK_ENV }}
        PORT: ${{ secrets.PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER }}
        CELERY_BACKEND: ${{ secrets.CELERY_BACKEND }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        CORREO: ${{ secrets.CORREO }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}

      
    
#    - name: Enviar resultados a Codecov #Envía los resultados del test de cobertura a Codecov para su visualización
#      run: |
#       pip install codecov
#        codecov
